import { Outfit } from "next/font/google";
import "./globals.css";
import UperBar from "./Components/UperBar/UperBar";
import SideBar from "./Components/SideBar/SideBar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Roadmap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
      <UperBar />
      <SideBar />
        {children}
      </body>
    </html>
  );
}
